@startuml

BROWSER->SERVER: GET https://studies.cs.helsinki.fi/exampleapp/spa
SERVER-->>BROWSER: HTML document
BROWSER->SERVER: GET https://studies.cs.helsinki.fi/exampleapp/main.css
SERVER-->>BROWSER: the CSS file
BROWSER->SERVER: GET https://studies.cs.helsinki.fi/exampleapp/spa.js
SERVER-->>BROWSER: the JavaScript file
Note right of BROWSER: the browser starts executing the JavaScript code that fetches the JSON from the server
BROWSER->SERVER: https://studies.cs.helsinki.fi/exampleapp/data.json
SERVER-->>BROWSER: [{"content":"hello","date":"2023-01-18T13:51:32.870Z"},....]




@enduml
    

